# Site settings
title: IVCF + RIT
email: ivcf@rit.edu
description: "Intervarsity Christian Fellowship at Rochester Institute of Technology"
baseurl: ""
copyright: "Intervarsity Christian Fellowship at RIT"
url: "http://ritivcf.github.io"
# pygments: true

# Build settings
markdown: kramdown
permalink: none

safe: true
lsi: false

# github: [Repository metadata]

github: ritivcf
twitter: ritivcf
facebook: ritivcf
youtube: RITivcf

exclude: [README.md, README.txt, LICENSE.txt, Gem*]

collections:
    smallgroups:
